version: 2
updates:
    # Maintain dependencies for GitHub Actions
    - package-ecosystem: "github-actions"
        directory: "/"
        schedule:
            interval: "weekly"

        # Disable PR creation for vulnerabilities
        open-pull-requests-limit: 5

        # Labels on pull requests for security and version updates
        labels:
            - "github-actions dependencies"

    # Maintain dependencies for npm
    - package-ecosystem: "npm"
        directory: "/" # Location of package manifests
        schedule:
            interval: "weekly"

        # Disable PR creation for vulnerabilities
        open-pull-requests-limit: 5

        # Labels on pull requests for security and version updates
        labels:
            - "npm dependencies"
